
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.7.0.0
//   File : devices_comm.cpp
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

#include "devices_reflection.h"
#include "devices_comm.h"
#include <bond/core/exception.h>

namespace microsoft
{
namespace azure
{
namespace devices
{
    
    const ::bond::Metadata Transport::Schema::metadata
        = ::bond::reflection::MetadataInit("Transport", "microsoft.azure.devices.Transport",
                ::bond::reflection::Attributes());
    
    const ::bond::Metadata Transport::Schema::s_Create_metadata
        = ::bond::reflection::MetadataInit("Create");
    
    const ::bond::Metadata Transport::Schema::s_Destroy_metadata
        = ::bond::reflection::MetadataInit("Destroy");

    
    const ::bond::Metadata Client::Schema::metadata
        = ::bond::reflection::MetadataInit("Client", "microsoft.azure.devices.Client",
                ::bond::reflection::Attributes());
    
    const ::bond::Metadata Client::Schema::s_CreateWithTransport_metadata
        = ::bond::reflection::MetadataInit("CreateWithTransport");
    
    const ::bond::Metadata Client::Schema::s_SendEventAsync_metadata
        = ::bond::reflection::MetadataInit("SendEventAsync");
    
    const ::bond::Metadata Client::Schema::s_SetMessageCallback_metadata
        = ::bond::reflection::MetadataInit("SetMessageCallback");
    
    const ::bond::Metadata Client::Schema::s_Destroy_metadata
        = ::bond::reflection::MetadataInit("Destroy");

    
} // namespace devices
} // namespace azure
} // namespace microsoft
